services:
  notes-app:
    image: roxsross12/simple-notes-app:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: simply-simple-notes
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge
    name: notes-network
